### ISSUE TITLE
위협 보고 유형 선택 페이지 + 로딩

### ISSUE THREAD

**Issue by mslee300** [osamhack2021/ai_web_RISKOUT_BTS#10]
## 페이지 1 - 위협 보고 유형 선택 및 로딩
- 페이지 디자인 및 퍼블리싱
- 주기 별로 위협 보고 기간 선택 가능 
- 로딩 중 동적 UI 렌더링
- 보고서 타입 선택 창

**Comment by playff** [comment]
세부 페이지 변경으로 인해 Closed
