### ISSUE TITLE
탐지현황 페이지 css 남은 수정사항

### ISSUE THREAD

**Issue by liboto00** [osamhack2021/ai_web_RISKOUT_BTS#142]
![탐지현황 페이지 수정사항](https://user-images.githubusercontent.com/89712521/136727073-ebf28d45-c045-4624-be84-3e18716fea22.PNG)

- [x]  FITER `font-family: "Noto sans KR", font-weight: 600, font-size: 1.5rem` 으로 변경

- [x]  FILTER RESET 높낮이 맞추기

- [x]  필터 체크박스 필터 내용 높낮이 맞추기

- [x]  검색 바 필터 바 높낮이 맞추기

- [x]  테이블 필드명 `"Noto sans KR"` font로 변경

- [x]  군사기밀, 허위기사 아이콘으로 변경

**Comment by simonseo** [comment]
폰트는 전체 테마에 한번에 적용할 수 있어서 이 방법으로 제가 하고 있습니다: https://mui.com/customization/theming/

**Comment by liboto00** [comment]
네 확인했습니다-! 나머지 수정사항도 다 같이 고민해보면 좋을 것 같습니다.

**Comment by liboto00** [comment]
모두 수정 완료해서 issue 닫겠습니다-!
