### ISSUE TITLE
탐지현황 목록 불러오기 실패 현상(TimeoutError 500)

### ISSUE THREAD

**Issue by Seo-Faper** [osamhack2021/ai_web_RISKOUT_BTS#150]
위협 탐지 현황 페이지의 페이지네이션 기능을 만들 던 중 실험을 위해 예제와 동일한 API를 이용해 JSON을 요청 했지만 ServerSelectionTimeoutError가 발생합니다.

요청 : 

```

method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Token ${token}`,
        },
        body: {
    "category": "news",
    "period": 72,
    "tags": { "PER": ["김정은"], "LOC": ["북한"] },
    "search_text": "노동신문",
    "limit": 7,
    "offset": 0
}

```

응답 : 

![image](https://user-images.githubusercontent.com/43310141/136807851-e597834c-4540-4c09-9191-1028e9cad8bd.png)

그래서 일단 /static/SecretData.example.json 을 복사해서 따로 추가한 json 파일을 만들어 개발 중이니 참고 하시면 될 것 같습니다.

**Comment by dev-taewon-kim** [comment]
`docker start mongo_service` 명령어 실행해서 MongoDB 실행하신거 맞습니까?
