### ISSUE TITLE
크롤링 병렬화 및 스크래핑한 내용 다듬기

### ISSUE THREAD

**Issue by flydog98** [osamhack2021/ai_web_RISKOUT_BTS#18]
## 크롤링 병렬화
일단 aiohttp를 이용하여 한 페이지(게시글 20개 목록)에 대해서는 병렬화가 되었지만, 여러 페이지에 대해서는 아직 구현이 안 되어 있다. 병렬화를 많이 할 수록 서버에 부담이 간다고 알고 있지만 일단 네이버니까 진행해 본다.
## 스크래핑한 내용 다듬기
★조정환 수병님에게 받은 책★을 적극 참고하여 원하는 정보를 아름답게 가져오고자 하는 목표가 있다.

- [x] 여러 페이지를 동시에 크롤링하기
- [x] 스크래핑한 내용(본문)을 다듬기

**Comment by simonseo** [comment]
병렬화 많이 할수록 서버에 부담이 가며, 그걸 막기 위해 서버 측에서는 크롤러의 IP대역을 차단하는 경우도 더러 있으니 조심해주세요!
