### ISSUE TITLE
다크 테마 적용시 PDF 배경에는 테마 미적용 버그

### ISSUE THREAD

**Issue by simonseo** [osamhack2021/ai_web_RISKOUT_BTS#181]
![image](https://user-images.githubusercontent.com/7032356/137122864-0bd04583-e2dd-43cd-9f9a-32904804bb58.png)

문제 원인은 알겠습니다. 
아마 추출 대상이 되는 요소에는 색이 적용되어있지 않고 상위 컨테이너 요소에만 테마가 적용되어 그런 것 같습니다.

**Comment by simonseo** [comment]
mui 테마 색으로 배경은 변경함. 
pdf 추출 시 패딩 및 버튼 삭제를 위해 pdf 추출을 함수형으로 변경할 예정

**Comment by playff** [comment]
원인은 mui 컴포넌트가 아닌 html 태그를 사용하여 그런 것 같습니다. 남은 코드 작성시 유의하여 주시기 바랍니다.

**Comment by simonseo** [comment]
PDF 추출할 때 모든 요소를 다 추출하는게 아니라 선택한 요소의 하위 요소들만 추출하는 형식입니다.
여기서 추출한건 mui <Box/> 요소였는데 mui에서 화면 렌더링을 할 때는 박스 요소에 딱히 배경색을 안 넣어줘서
그 요소만 추출할 때 배경색이 없게 나오는 문제였습니당.

버튼은 안 보이게 숨김. 문제 해결되어 이슈 닫습니다.
