### ISSUE TITLE
언어 모델 선택은 어떤 기준으로 하는지

### ISSUE THREAD

**Issue by playff** [osamhack2021/ai_web_RISKOUT_BTS#2]
BERT 등의 사전학습된 모델들을 사용하는게 최선의 방법인지 궁금합니다.
퀄리티는 보장되겠지만 속도 등의 문제로 trade-off 가 생기지 않을까 싶은데 여러 모델을 포함하는 프로젝트인만큼 그 부분에 대해 잘 고민해보면 좋을 것 같습니다.

**Comment by simonseo** [comment]
- 위협보고
- 기밀 유출 현황
- 허위 정보 검사

이 3가지 주요 기능 중에 실시간으로 모델을 실행해야 하는 기능은 `허위 정보 검사` 정도겠네요.
NLP모델들은 잘 모르지만 라이트버트 같은 모델 사용하면 정확도 차이가 심할까요?

그리고 BERT를 그대로 쓰실 생각이신가요 아니면 버트 기반으로 더 훈련시키실 생각이신가요?

**Comment by playff** [comment]
1. "라이트버트 같은 모델 사용하면 정확도 차이가 심할까요?"
- `DistilBERT` 와 같은 경량화 모델을 쓰는 것이 확실히 좋아보입니다! (BERT 대비 크기는 40% 감소, 이해능력은 97% 유지, 속도 60% 상승라고 합니다).
- [DistilKobert](https://github.com/monologg/DistilKoBERT) 라는 `pretrained model`을 찾아서 이걸로 시도해봐도 좋을 것 같네요. 의견 감사합니다.

2. "BERT를 그대로 쓰실 생각이신가요 아니면 버트 기반으로 더 훈련시키실 생각이신가요?"
- 현재 "허위 정보 검사" 기능은 한국어 데이터셋이 마땅치 않아보여 [SNU FactCheck](https://factcheck.snu.ac.kr/)에서 직접 데이터셋을 만들어 볼 예정이고, 여러 기법들을 비교해보면서 `test set`에 대해 정확도가 더 높은 방법을 적용해볼 예정입니다. (추론 속도 또한 비교해가면서)
- 시험해 볼 가설들
  - TF-IDF
  - Word2Vec
  - BERT 
  - etc..
