### ISSUE TITLE
(프론트 필독) 검색 자동완성 기능 구현 방법에 대하여

### ISSUE THREAD

**Issue by dev-taewon-kim** [osamhack2021/ai_web_RISKOUT_BTS#35]
검색 자동완성 기능 관련해서 자료를 많이 찾아봤는데 네이버나 구글처럼 빅데이터를 처리하는 경우에는 백엔드와 통신하면서
 자동완성을 하지만 데이터의 크기가 작은 경우에는 대부분 프론트에서 자동완성을 구현하는 것 같습니다.

검색 자동완성을 백엔드에서 하게 되면 아래와 같은 문제가 야기될 수 있다고 생각합니다.

- Q1.  Request를 언제 보낼 것인가?
  - 1-1. 만약 사용자가 검색창에 한 글자 입력할 때마다 보낸다고 하면 Response를 받아오는 시간이 있어서 딜레이가 예상됨

  - 1-2. 게다가 크롤링 된 RAW 데이터, Post-processing된 데이터는 Django의 DB와 분리된 별도의 DB에 저장되는데 그러면
          Django에서 해당 데이터를 변수에(메모리에) 저장해놓고 Response를 해줘야 하는지?
          그게 아니라면 매번 쿼리 날려서 DB에 조회를 해줘야 하는지?

  - 1-3. 결국 너무 느릴 것 같다는 얘기입니다.
 
 
그래서 제가 생각한 Solution입니다.

- Sol1. 어차피 데이터의 양이 그렇게 많지 않으니까 필요한 데이터를 한 번에 프론트에 보내고, 자동완성 기능을 프론트에서 구현
  - 1-1. 찾아보니까 react에 관련 라이브러리가 다수 존재함. 아래는 예시

  - 1-2. [https://github.com/AmyShackles/react-autosuggestions](https://github.com/AmyShackles/react-autosuggestions)
  
  - 1-3. (Demo) [https://codesandbox.io/s/react-autosuggestions-example-3u13v?file=/src/App.js](https://codesandbox.io/s/react-autosuggestions-example-3u13v?file=/src/App.js)
  
- Sol2. 만약에 데이터의 양이 한 번에 받아오기에는 많다고 하면 Pagination을 해서 일부만 받아오게 될 가능성이 높음
   - 2-1. 따라서 프론트단에서는 모든 데이터를 가지고 있지 않아서 자동완성 기능 구현이 불가능함.
   
   - 2-1. 하지만 우리 프로젝트에서 검색어로 들어갈 데이터는 결국 키워드(e.g. SLBM, 한미연합훈련)일테니까 
            사용자 지정 데이터(i.e. 기간, 카테고리)에 포함된 모든 키워드를 Trie로 만들어서 프론트에 전달한다면? 
            
   - 2-2. 이렇게 하면 우리 프로젝트의 데이터 크기면 키워드의 Trie 크기는 매우 작을 것으로 예상됨.
     

나름 많이 찾아보고 공부도 하고 생각도 많이 해봤는데 제 개인적인 생각으로는 **우선 Sol1을 시도해 보고 
프론트단에서 최적화가 어려울 정도로 느리거나, 데이터를 받아오는 속도 자체가 너무 느리다고 하면 Sol2를 시도**해 보는게 
어떨까 싶습니다.

프론트 수병님들의 의견, 특히 @simonseo 의 의견을 듣고 싶습니다.

**Comment by simonseo** [comment]
제 생각에도 sol1이 괜찮아보이네요
