### ISSUE TITLE
WordCloud 라이브러리 선택하기

### ISSUE THREAD

**Issue by simonseo** [osamhack2021/ai_web_RISKOUT_BTS#36]
**옵션 1**
https://wordcloud2-js.timdream.org/#web-tech
https://openbase.com/js/wordcloud/documentation

**옵션 2**
https://codesandbox.io/embed/react-d3-cloud-demo-forked-50wzl
https://openbase.com/js/react-d3-cloud/documentation

**Comment by playff** [comment]
wordcloud2-js 가 개인적으로 좋아보이네요. 너무 정적이지도 않고 좋은 선택인 것 같습니다!
