### ISSUE TITLE
백엔드 쪽으로 /api/login/ 또는 /api/register/에 POST로 값을 넘기는데 장고 서버 로그에 400 Bad Request라고 뜹니다

### ISSUE THREAD

**Issue by simonseo** [osamhack2021/ai_web_RISKOUT_BTS#38]
백엔드 쪽으로 /api/login/ 또는 /api/register/에 POST로 값을 넘기는데 장고 서버 로그에 400 Bad Request라고 뜹니다. postman에 있는 거 보고 그대로 전송해도 안되네요..

_Originally posted by @Seo-Faper in https://github.com/osamhack2021/ai_web_RISKOUT_BTS/issues/28#issuecomment-925267094_

**Comment by dev-taewon-kim** [comment]
https://github.com/osamhack2021/ai_web_RISKOUT_BTS/tree/feature/front-user-auth/WEB 

혹시 여기에 backend 폴더가 없는 이유를 설명해주실 수 있을까요...

**Comment by dev-taewon-kim** [comment]
@simonseo 그.. @Seo-Faper 가 실수로 /feature/frontend-boilerplate 에서 작업하고 push까지 해버렸다고 해서 
기존 front-user-auth 브랜치 삭제하고 boilerplate 브랜치에서 다시 front-user-auth 이름으로 브랜치 새로 만들었습니다.

그래서 보일러플레이트 브랜치에 로그인 관련 데이터들 있을건데 이거 어떻게 해야 할지 모르겠네요...

걍 냅둘지 아니면 git 활용해서 이전 버전으로 돌려놓을지 아니면 그냥 수동으로 삭제하고 새로 push 할지....

Simon! 날 보고 있다면! 정! 답을 알려줘!

**Comment by dev-taewon-kim** [comment]
@simonseo 이 /feature/frontend-boilerplate 에 로그인 관련 데이터들 있는거 상관없다고 합니다. 

암튼 front <-> backend 통신 오류는 해결했습니다.

@Seo-Faper 한테도 잘 설명해줬습니다.
