### ISSUE TITLE
NER 기능 output data의 label에 대해 궁금한 점이 있습니다!

### ISSUE THREAD

**Issue by dev-taewon-kim** [osamhack2021/ai_web_RISKOUT_BTS#44]
{
  "ner": [
    {
      "ORG-B": [
        "넷플릭스"
      ],
      "LOC-B": [
        "한국"
      ],
      "CVL-B": [
        "피해자",
        "오징어",
        "지인"
      ],
      "AFW-B": [
        "투데이"
      ],
      "PER-B": [
        "영문"
      ],
      "FLD-B": [
        "드라마"
      ],
      "TIM-B": [
        "밤낮"
      ]
    }
  ],
  "time": 2.763068914413452
}

에서 ORG-B는 Organization 인 것 같고, LOC-B는 Location 인 것 같은데 이해가 안되는 label들이 다수 있습니다.

그리고 나올 수 있는 label이 더 뭐가 있는지, 그리고 그게 무슨 의미인지 궁금한데 혹시 해당 내용 정리된 
official docs 같은게 있는지 궁금합니다.

아 그리고 A, B, C 이런식으로 나오는건 그냥 해당 label에서 유사한 entity끼리 clustering? 해놓은 것 같은데 맞습니까?

api 설계중인데 막히는 부분이라서 질문드립니다!

**Comment by playff** [comment]
먼저 데이터셋에 대해서 설명을 해드리면 [naver/nlp-challenge](https://github.com/naver/nlp-challenge)를 선택하였습니다. 

그리고 데이터셋에 대한 [리더보드](http://air.changwon.ac.kr/?page_id=10)를 들어가보면 카테고리가 설명이 되어있는데 아래와 같이 나눠 집니다.

|   |  개체명 범주  |  태그  |  정의 |
|--|:--:|:--:|:--:|
1 | PERSON | PER | 실존, 가상 등 인물명에 해당 하는 것 |
2 | FIELD | FLD | 학문 분야 및 이론, 법칙, 기술 등 | 
3 | ARTIFACTS_WORKS | AFW | 인공물로 사람에 의해 창조된 대상물 |
4 | ORGANIZATION | ORG | 기관 및 단체와 회의/회담을 모두 포함 |

**Comment by playff** [comment]
**혹시 해결되셨다면 Close 부탁드립니다~**
