### ISSUE TITLE
Crawler column 추가 요청

### ISSUE THREAD

**Issue by dev-taewon-kim** [osamhack2021/ai_web_RISKOUT_BTS#52]
* 중복 크롤링 방지를 위해 article_id를 저장하는 것과 유사한 이유로 isAnalyzed column이 필요합니다.

* column명은 isAnalyzed, 타입은 Boolean으로 부탁 드립니다.
* 기본 값은 반드시 **False**로 지정해주셔야 합니다.
* 이미 분석이 된 데이터는 Analyzer에서 raw_data DB(SQLite)의 isAnalyzed 값을 True로 지정할 예정입니다.

**Comment by flydog98** [comment]
내일 바로 해결해 놓도록 하겠습니다.
필승필승!
