### ISSUE TITLE
네이버 뉴스 크롤링 데이터 요청

### ISSUE THREAD

**Issue by playff** [osamhack2021/ai_web_RISKOUT_BTS#64]
### 사용목적
- `프론트` : 사용할 `더미 데이터` 제공
- `AI` : 거짓 뉴스를 탐지를 위한 `데이터셋` 제공 
  - 현재 snu factcheck 에서 3000개 가량의 데이터를 긁어왔지만 가짜뉴스와 아닌 것의 데이터 개수 차이가 커 데이터 분포를 맞춰주기 위함 + 데이터 셋 늘려 정확도 올리기

### 제공 파일 형식
- CSV 로 제공해주시면 좋겠지만, 기존에 사용중인 sqlite 파일 형식으로 주셔도 됩니다. : )

**Comment by flydog98** [comment]
30일 퇴근 전까지 만들어 놓겠습니다. 필승필승

**Comment by flydog98** [comment]
일단 940개의 데이터를 feature/cralwer브랜치의
`WEB/backend/crawler/crawler/database.db` 파일에 넣는데는 성공했습니다.

**Comment by playff** [comment]
감사합니다. 다른분들도 활용해주세요~
