### ISSUE TITLE
전 페이지 디자인 및 퍼블리싱

### ISSUE THREAD

**Issue by mslee300** [osamhack2021/ai_web_RISKOUT_BTS#7]
- [x]  전 페이지 디자인 목업
- [x]  HTML, CSS, Javascript로 퍼블리싱
- [x] #32

**Comment by simonseo** [comment]
`feature/publishing` 브랜치를 `develop`에서 새로 만드셔서 `WEB/publishing` 폴더를 만드시고 그 안에 퍼블리싱하신거 넣어주시면 아주 좋을 것 같습니다.

**Comment by mslee300** [comment]
요청하신 작업 완료 했습니다. @simonseo

**Comment by simonseo** [comment]
feature/publishing -> feature/develop 풀리퀘스트 만들어주세요!
