### ISSUE TITLE
비밀번호 초기화 기능 구현 중 질문

### ISSUE THREAD

**Issue by Seo-Faper** [osamhack2021/ai_web_RISKOUT_BTS#71]
현재 계정에 연결된 이메일을 입력하면 해당 이메일로 임시 비밀번호를 전송해 주는 기능을 구현 하고 있는데요.
![1](https://user-images.githubusercontent.com/43310141/135443965-c86287d7-3cbb-4fda-9016-e65cff5fd2eb.PNG)
이렇게 이메일은 정상적으로 오는데..

![2](https://user-images.githubusercontent.com/43310141/135443970-df582422-809e-44ee-b988-9ed2922f5f35.PNG)

안에 내용은 임시 비밀번호가 아니라 토큰 값을 줍니다.

어떻게 하면 임시 비밀번호가 이메일에 적히게 할 수 있나요?

**Comment by simonseo** [comment]
어떤 브랜치에서 작업 중이시죠? 한번 볼게요!!

**Comment by Seo-Faper** [comment]
feature/user-auth 에서 작업 중 입니다.
한번 읽어보고 다시 만들어 보겠습니다.

**Comment by Seo-Faper** [comment]
이메일은 
/api/password_reset/ 으로 바로 보냈습니다.

**Comment by dev-taewon-kim** [comment]
제가 했어야 할 답변을 @simonseo 이 해주셨네요.

비밀번호 초기화는 

1. ```/api/password_reset```으로 요청을 보내면 이메일로 토큰이 옵니다. (아직 도메인 세팅이 되지 않아서 도메인 부분은 ```''```입니다.)

2. ```/api/password_reset/confirm```으로 토큰이랑 변경할 비밀번호를 담아 요청을 보내면 비밀번호가 변경됩니다.

# Front-Workflow

1. 프론트 로그인 모달에서 비밀번호 찾기 링크를 클릭합니다.

2. 해당 링크를 입력하면 이메일을 입력할 수 있는 폼이 뜹니다.

3. 해당 폼에서 이메일 입력 후 submit 하면  ```/api/password_reset```으로 요청을 보내고 백엔드에서 이메일로 비밀번호 초기화 링크를 보내줍니다.

4. 사용자가 이메일로 온 링크를 클릭하면 비밀번호를 변경할 수 있는 폼이 뜹니다. (비밀번호, 비밀번호 확인 input 필요)

5. submit 하면 get 파라미터로 받았던 token과 사용자가 입력한 password를 ```/api/password_reset/confirm```으로 보냅니다.

6. 반환 값을 확인해서 성공 or 실패 메시지를 띄웁니다.

**Comment by dev-taewon-kim** [comment]
그리고 dev에 있는 거 올려서 테스트 해봤는데 로그인은 서버에서 정상적으로 토큰을 발급해줬는데 

```아이디 또는 비밀번호를 확인해주세요.``` 오류가 발생합니다.

회원가입도 마찬가지로 서버에 정상적으로 데이터가 insert 됐는데 
```사용불가능한 아이디입니다.``` 오류가 발생합니다.

어려운 부분이 있으시면 최대한 빨리 issue 남겨주시거나 slack으로 도움 요청해주시면 감사하겠습니다.

**Comment by Seo-Faper** [comment]
제가 feature/user-auth 브랜치에서만 작업 중이라서 코드를 비교해 본 결과  develop 브랜치에는 아직 제가 만든 부분이 적용되지 않은 것 같습니다.

변경 사항이 생기면feature/user-auth  뿐만 아니라 develop 브랜치에도 push해도 되나요? 
develop 브랜치와 feature/user-auth  브랜치의 차이점을 간략히 설명 해 주실 수 있으신지..

**Comment by playff** [comment]
Develop 브랜치에는 push하시면 안됩니다! 현재 구현중인 작업을 완료하시면 PR을 날려서 확인 후 merge를 하는 겁니다. 다시말하면 develop 브랜치는 각 feature 내에서 구현이 완료된걸 나중에 머지시키는 나무의 줄기라고 생각하시면 될 것 같네요. 만약 종찬씨가 지금 feature/user-auth를 완료하셨다면 merge 명령어로 develop 브랜치를 로컬에서 합쳐보고 conflict(코드 충돌) 이 나는 부분을 수정 후에 깃헙 내에서 pull request(pr)을 요청하면 됩니다!. 그 후에는 팀원 중 누군가가 검토 후에 develop 브랜치로 머지시키고 기존에 사용하던 feature 브랜치는 날리게 되는거죠

**Comment by playff** [comment]
최대한 자세히 설명해보려 했지만.. 충분하지 않은 것 같아.
구글에서 git flow 전략과 git merge에 대해서 찾아보시면 도움이 될 것 같습니다! 해결 안되시는 부분은 슬랙으로도 남겨주세요

**Comment by Seo-Faper** [comment]
알겠습니다. 참고하겠습니다!
