### ISSUE TITLE
검색 바 스타일링

### ISSUE THREAD

**Issue by simonseo** [osamhack2021/ai_web_RISKOUT_BTS#80]
검색 바 높낮이가 안 예쁜데 수정해주세요!

**Comment by liboto00** [comment]
네 알겠습니다~!

**Comment by liboto00** [comment]
![search bar](https://user-images.githubusercontent.com/89712521/135972105-2794878c-518a-41ec-9de3-e09ce8388a1d.PNG)
feature/front-temp-side-navi에서 수정했습니다.
높낮이 어떤가요?

**Comment by simonseo** [comment]
아주 좋습니당!
