### ISSUE TITLE
크롤러 본문 길이 검증 로직 추가 요청

### ISSUE THREAD

**Issue by dev-taewon-kim** [osamhack2021/ai_web_RISKOUT_BTS#83]
```CRAWL_DATEAMOUNT = 30```으로 설정 후 테스트해봤는데 속보 같은 경우는 본문 내용이 매우 짧아 NLP 서버에서 null값을 return해서 문제가 발생합니다.

# Suggestion

* ```WEB/backend/crawler/crawler/model/Content.py```

```py
...

try:
    body_div = soup.find(contents_page.body_div, class_=contents_page.body_div_class)
    body = str.strip(body_div.get_text())
===>
    if not (100 < len(body) < 2000):
        raise ContentLengthError
===>
except AttributeError:
    body = "내용이 없습니다."

...
```

* ```WEB/backend/crawler/crawler/error.py```

```py
...

class englishContentError(Exception):
    def __init__(self):
        self.msg = "english content discovered"

    def __str__(self):
        return self.msg
===>
class ContentLengthError(Exception):
    def __init__(self):
        self.msg = "Content too short or too long (100 < string < 2000)"

    def __str__(self):
        return self.msg
===>

```

그리고 많은 양의 데이터를 처리할 때 print문이 리소스를 너무 많이 잡아먹습니다.
디버깅용으로 넣으신 print문들 주석 처리 후 push 해주시고, 디버깅 하실 때만 잠깐 주석 풀어서 쓰시면 될 것 같습니다.

**Comment by flydog98** [comment]
print문 같은 경우에는 backend/crawler/crawler/setting.py에 있는 DEBUG를 False로 만드시면 출력되지 않으니 참고바랍니다!

**Comment by flydog98** [comment]
그리고 Conetnts.py를 수정하면 뉴스 말고 커뮤니티 글 역시 100자 이하는 읽히지 않는데, 이것 역시 의도하는 바인지 궁금합니다.

**Comment by playff** [comment]
커뮤니티 글이 요약이 필요한가에 대한 생각도 드네요

**Comment by flydog98** [comment]
사실 제 생각도 그렇습니다. 일단 다른 방향으로 뉴스만 100자 이상 읽도록 해 보겠습니다.

**Comment by flydog98** [comment]
일단 테스트까지는 완료했는데, 2000자 이상도 에러가 나는지, 그냥 suggestion만 보고 2000자로 설정해서 드리면 되는 건지 두 가지가 궁금합니다.

**Comment by playff** [comment]
https://github.com/pytorch/fairseq/issues/1685
를 참고하시면 좋을 것 같은데 결론적으로는 모델 학습을 다시 시키지 않는 한 불가능할 것으로 보입니다

**Comment by playff** [comment]
1024가 그리고 서브토큰의 개수라 정확히 말하면 단어 청크에 가까워 딱 이정도라고 말하기도 어렵네요

**Comment by dev-taewon-kim** [comment]
> 관련 이슈 좀 읽고 자세히 알려드리겠습니다
> 
> 일단 이런 문제 때문에 문장생성을 하는 abstractive 모델 대신.. 추출을 하는 extractive 모델로 바꾸려 하였으나 이것저것 하면서 우선순위가 밀린것 같네요. 해결 방안은
> 
> 1. 길이가 길면 쪼개서 현재 모델을 돌린다 (매우 비싼 연산)
> 2. Extractive 모델을 사용한다.
> 3. 문서의 앞쪽에 주요 내용이 있길 빌며 1024개 토큰으로 쪼갠다.
> 
> 인데 고민을 해보겠습니다

2000자 이하는 문제 없이 작동하는겁니까?
