### ISSUE TITLE
크롤러 길이 검증 로직 변경 요청 (2차)

### ISSUE THREAD

**Issue by dev-taewon-kim** [osamhack2021/ai_web_RISKOUT_BTS#89]
```
(평양 노동신문=뉴스1) = 북한은 전날인 29일 열린 최고인민회의 제14기 제5차 회의 2일 회의에서 인사를 단행했다고 30일 당 기관지 노동신문이 보도했다. 김성남 당 국제부장이 새 국무위원회 위원에 이름을 올렸다.   [국내에서만 사용가능. 재배포 금지. DB 금지. For Use Only in the Republic of Korea. Redistribution Prohibited] rodongphoto@news1.kr
```
이게 무려 239자입니다. 쓰레기 값 제외하면 두 문장 짜리 기사인데도 그렇습니다.

당연히 NLP에서 오류 발생해서 null값 리턴합니다.

~~따라서 길이 검증 로직의 최솟값을 기존 `100`에서 `400`으로 상향 요청합니다.~~
* 추가 : @playff 님의 말씀대로  **길이 검증 로직의 최솟값을 기존 `100`에서 `600`으로 상향 요청합니다.**

**Comment by playff** [comment]
로컬에서 테스트해보고 답변드리겠습니다.

**Comment by playff** [comment]
저희 데이터로 길이 평균을 내본 결과 987 자 정도로 나왔고, 그 아래 대부분 기사들은 위에 올려주신 기사와 같은 형식인 걸로 판단이 됩니다.  그래서 의미 있는 기사들만 가져오기 위해선 600자 까지도 상향시켜도 될 것으로 보입니다.

**Comment by flydog98** [comment]
오늘 연등때 해결하겠습니다.

**Comment by dev-taewon-kim** [comment]
> 오늘 연등때 해결하겠습니다.

추가로 하루에 몇 개의 데이터를 크롤링 할 지도 설정할 수 있었으면 합니다.

오늘 날짜 기준으로 300개면 4일 분량입니다.

같은 300개라고 해도 4일 분량 300개 보다는 하루에 10개씩 30일 분량이 더 좋다고 생각합니다.

**Comment by flydog98** [comment]
근데 갑자기 든 의문인데, 요약이 더 이상 필수적인 과정이 아니게 된다면 크롤링 개수 제한이 필요한가요>??

**Comment by flydog98** [comment]
일단 크롤링 개수 제한은 유지하지만, 장기적으로 없앨 계획을 구두로 합의하였습니다. 따라서 하루 당 데이터 크롤링할 개수를 정하는 로직은 추가되지 않고, 300개 제한 역시 없앨 계획입니다. 코드만 지우면 되므로 없애는 것은 쉽습니다.

**Comment by flydog98** [comment]
크롤링 개수 제한 로직 역시 주석 처리했습니다.
