### ISSUE TITLE
도커라이징 및 배포

### ISSUE THREAD

**Issue by mslee300** [osamhack2021/ai_web_RISKOUT_BTS#9]
**프로젝트 도커라이징 및 베포**
개발환경의 일원화, 기술환경 세팅의 효율화를 위해 도커라이징 작업

- [x] NLP Module
- [x] Crawler Module
- [x] Django Backend
- [x] React Frontend

**Comment by simonseo** [comment]
가장 최근 풀리퀘를 봤을 때 NLP 모듈은 도커라이징을 훌륭하게 해주신 것 같습니다.
