### ISSUE TITLE
DB 및 크롤링 항목에 날짜 추가

### ISSUE THREAD

**Issue by flydog98** [osamhack2021/ai_web_RISKOUT_BTS#93]
DB와 크롤링해주는 항목에 컨텐츠의 생성 날짜를 추가해 달라는 요청을 받았습니다.
그!러!나!
코드스페이스가 갑자기 켜지지 않는 문제에 직면하여 코드를 수정할 수 없는 상황입니다.
일단은 repl.it 등에서 수정해서 테스트 후 깃허브에 직접 입력하는 방식을 생각중이긴 합니다.
(branch파서 직접 수정 후 PR을 넣는 방식)

**Comment by dev-taewon-kim** [comment]
codespace 문제 해결되었습니다.
